/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.productApp

class App {
    String getGreeting() {
        return 'Hello World!'
    }

    static void main(String[] args) {
        Product product = new Product("Kanche","Kanche de marlo",30);
        println(product.getName());
        println(product.getDescription());
        println(product.getPrice());

        println new App().greeting
    }
}
